name: CI (client)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  packages:
    name: Install node_modules
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: cd client && npm ci
  build:
    name: Client Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run build
  lint:
    name: Client Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run lint
  type-check:
    name: Client Type Check
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run type-check
  test:
    name: Client Test
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 18.x
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run test
