name: CI (client)

on: [push, pull_request]

jobs:
  packages:
    name: Install node_modules
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - run: cd client && npm ci
  build:
    name: Client Build
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run build
  lint:
    name: Client Lint
    runs-on: ubuntu-latest
    needs: [packages]
    env:
      CI: true
      NODE_ENV: production
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: client/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - run: cd client && npm run lint
